- name: Create VM
  hosts: localhost
  roles:
  - role: proxmox-ansible
    vars:
    action: create_vm
    proxmox_host: 192.168.124.4:8006
    proxmox_user: root@pam
    proxmox_pass: H0laMund0*
    vm_name: presentacion
    cpu_sockets: 1
    cpu_cores: 1
    ram_mb: 2048
    disk_gb: 50
    vlan: 1
    datastore: CEPH_Pool_data
    template_name: Presentacion
    proxmox_node: pve1
    network_mac_addr: "AA:AA:AA:01:00:20"
    network_bridge: vmbr0

- name: Create user and make it sudoer
  hosts: testvm95
  become: yes

  tasks:
    - name: Create new user
      user:
        name: TEST
        state: present

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "TEST ALL=(ALL) NOPASSWD:ALL"
        validate: /usr/sbin/visudo -cf %s
