- name: Create VM
  hosts: localhost
  roles:
  - role: proxmox-ansible
    vars:
    action: create_vm
    proxmox_host: 192.168.124.4:8006
    proxmox_user: root@pam
    proxmox_pass: H0laMund0*
    vm_name: "{{ nombre_vm }}"
    cpu_sockets: 1
    cpu_cores: "{{ nucleos_cpu }}"
    ram_mb: "{{ mb_ram }}"
    disk_gb: 50
    vlan: 1
    datastore: CEPH_Pool_data
    template_name: resulta2
    proxmox_node: pve1
    network_mac_addr: "AA:AA:AA:01:00:20"
    network_bridge: vmbr0
